# Generated by Django 3.1.6 on 2021-02-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainTable',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Organi', models.CharField(max_length=200)),
                ('Account', models.CharField(max_length=200)),
                ('Curr', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('Counterparty', models.CharField(max_length=200)),
                ('Agreement', models.CharField(max_length=200)),
                ('Balance', models.IntegerField(default=0)),
                ('Inflow', models.IntegerField(default=0)),
                ('Outflow', models.IntegerField(default=0)),
                ('week', models.IntegerField(default=0)),
                ('month', models.CharField(max_length=200)),
                ('year', models.IntegerField(default=0)),
            ],
        ),
    ]
